# Generated by Django 6.0.2 on 2026-05-04 13:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diyprojects', '0002_profile_favorite_projectrating_projectreview'),
    ]

    operations = [
        migrations.AddField(
            model_name='projectrating',
            name='project',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ratings', to='diyprojects.project'),
        ),
    ]
