# Generated by Django 6.0.2 on 2026-05-04 18:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diyprojects', '0003_projectrating_project'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='name',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='short_bio',
        ),
        migrations.AddField(
            model_name='profile',
            name='display_name',
            field=models.CharField(default='New User', max_length=63),
        ),
        migrations.AddField(
            model_name='profile',
            name='role',
            field=models.TextField(default='Standard User', max_length=63),
        ),
        migrations.AddField(
            model_name='project',
            name='creator',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='diyprojects.profile'),
        ),
        migrations.AddField(
            model_name='projectreview',
            name='project',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='project_reviews', to='diyprojects.project'),
        ),
        migrations.AlterField(
            model_name='favorite',
            name='date_favorited',
            field=models.DateField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='favorite',
            name='project_status',
            field=models.CharField(choices=[('Backlog', 'Backlog'), ('To-Do', 'To-Do'), ('Done', 'Done')], max_length=10),
        ),
    ]
