# Generated by Django 6.0.2 on 2026-05-04 18:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diyprojects', '0004_remove_profile_name_remove_profile_short_bio_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projectreview',
            name='project',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='diyprojects.project'),
        ),
        migrations.AlterField(
            model_name='projectreview',
            name='reviewer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='diyprojects.profile'),
        ),
    ]
