# Generated by Django 6.0.2 on 2026-05-06 16:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diyprojects', '0005_alter_projectreview_project_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='favorite',
            name='project_status',
            field=models.CharField(choices=[('B', 'Backlog'), ('TD', 'To-Do'), ('D', 'Done')], max_length=10),
        ),
        migrations.AlterField(
            model_name='projectreview',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
        migrations.AlterUniqueTogether(
            name='projectrating',
            unique_together={('profile', 'project')},
        ),
    ]
