# Generated by Django 6.0.2 on 2026-05-02 14:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('merchstore', '0004_product_image_product_owner_alter_transaction_buyer_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='amount',
            field=models.IntegerField(),
        ),
    ]
